### ISSUE TITLE
WorkFlow Error on installing Embedded Arm Toolchain

### ISSUE THREAD

**Issue by A4EVA** [lupyuen/pinetime-logo-loader#2]
Hello, 

I was trying to follow the instructions to have github workflow building the image for me. I forked the repo as described and tried one of the samples in the logos folder. The build process begins and after a while it stops on Install Embedded Arm Toolchain, you'll see a picture below:

![Workflow_error](https://user-images.githubusercontent.com/4736991/185091911-792a74be-dafd-4c62-bac6-a23907a28e01.PNG)

I do not know what I'm doing wrong

**Comment by lupyuen** [comment]
Hi: Sorry I'm no longer maintaining this project. Perhaps we could look for the updated instructions to load the InfiniTime Boot Logo?

This looks relevant, but I'm not sure if it's up-to-date:

https://pfeerick.github.io/InfiniTime/bootloader/

Thanks!

**Comment by A4EVA** [comment]
Hello Sir,
thank you so much for your reply, I'm honoured to read you, I read the documentation present in the bootloader folder of the infinitime repo and I read about the pinetime-graphics option, the only problem is that in CMakeLists.txt this option has disappeared. To be honest I hav not understood how I have to change the boot logo for the PineTime

**Comment by lupyuen** [comment]
I see that the InfiniTime Team is working on your issue: https://github.com/InfiniTimeOrg/InfiniTime/issues/1290

I hope they'll respond soon :-)

**Comment by JF002** [comment]
I replied :) Basically : the graphic is now built in the bootloader firmware. If you want to change the picture, you'll have to rebuild the bootloader with the new picture. This is a change I made when I added the recovery firmware functionality.

**Comment by lupyuen** [comment]
Ah that makes sense. Thanks JF :-)
